config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: 'app', as: 'app' do
    root to: 'app#index'

    resources :sessions, only: %i[new create]
    resources :verifications, only: %i[new create]
    resource :setup, controller: 'setup', only: %i[show]
    resources :settings, only: %i[index show]


    namespace :signup do
      resource :stage_one, controller: 'stage_one', only: %i[new create]
      resource :stage_two, controller: 'stage_two', only: %i[new create]
      resource :stage_three, controller: 'stage_three', only: %i[new create]
      resource :complete, controller: 'complete', only: %i[show]
    end

    scope module: 'static_content' do
      get :about
    end
  end
end

app/models/activity.rb
# frozen_string_literal: true

class Activity < ApplicationRecord
  belongs_to :subject, polymorphic: true
  belongs_to :seen_by, optional: true

  validates :subject, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication_code.rb
# frozen_string_literal: true

class AuthenticationCode < ApplicationRecord
  validates :phone_number, :code, presence: true

  scope :active, -> { where(expired: false) }
end

app/models/couple.rb
# frozen_string_literal: true

class Couple < ApplicationRecord
  belongs_to :person_a, class_name: Person.name, dependent: :destroy
  belongs_to :person_b, class_name: Person.name, dependent: :destroy
  belongs_to :wedding

  has_one_attached :picture

  validates :person_a, :person_b, :wedding, presence: true
end

app/models/domain.rb
# frozen_string_literal: true

class Domain < ApplicationRecord
  belongs_to :wedding

  validates :wedding, :hostname, presence: true
  validates :hostname, uniqueness: true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :venue, optional: true

  validates :starts_at, :details, presence: true
end

app/models/guest.rb
# frozen_string_literal: true

class Guest < ApplicationRecord
  belongs_to :invite

  validates :invite, presence: true
end

app/models/invite.rb
# frozen_string_literal: true

class Invite < ApplicationRecord
  belongs_to :wedding

  validates :wedding, presence: true
end

app/models/login_session.rb
# frozen_string_literal: true

class LoginSession < ApplicationRecord
  belongs_to :person

  validates :person, presence: true

  scope :valid, -> { where(invalidated: false) }
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  has_one :couple_as_person_a, class_name: Couple.name, foreign_key: :person_a_id
  has_one :couple_as_person_b, class_name: Couple.name, foreign_key: :person_b_id
  has_many :login_sessions
  has_many :seen_activities,
           class_name: Activity.name,
           foreign_key: :seen_by_id,
           dependent: :destroy

  validates :forename, :surname, presence: true
  validates :mobile_phone_number, uniqueness: true

  def couple
    Couple.where(person_a_id: id).or(Couple.where(person_b_id: id)).first!
  end
end

app/models/venue.rb
# frozen_string_literal: true

class Venue < ApplicationRecord
  has_many :events, dependent: :nullify

  validates :name,
            :address_line_1,
            :city,
            :county,
            :postcode,
            :country,
            presence: true
end

app/models/wedding.rb
# frozen_string_literal: true

class Wedding < ApplicationRecord
  belongs_to :primary_domain, class_name: Domain.name
  has_one :couple, dependent: :destroy
  has_many :people, through: :couple
  has_many :domains, dependent: :destroy

  validates :name, :date, :primary_domain, :couple, presence: true
end

app/controllers/app/app_controller.rb
# frozen_string_literal: true

module App
  class AppController < BaseController
    def index
      redirect_to app_setup_path if logged_in?
    end
  end
end

app/controllers/app/base_controller.rb
# frozen_string_literal: true

module App
  class BaseController < ApplicationController
    layout 'app'

    private

    def registry
      @registry ||= Services::PerRequestRegistry.new(cookies)
    end

    delegate :authentication_persistence,
             :messaging_service_provider,
             :session_manager,
             to: :registry

    def authentication_helpers
      @authentication_helpers ||= Services::AuthenticationHelpers.new(session_manager)
    end

    delegate :current_user,
             :current_wedding,
             :logged_in?,
             to: :authentication_helpers

    def self.requires_user_to_be_logged_in
      before_action :redirect_to_login_if_signed_out
    end

    def redirect_to_login_if_signed_out
      return true if logged_in?
      flash[:error] = 'You need to be logged in to continue'
      redirect_to new_app_session_path
    end

    def self.uses_navigation_screen
      before_action :prepare_navigation
    end

    def prepare_navigation
      @navigation = Presenters::Navigation.new(request.path)
    end
  end
end

app/controllers/app/sessions_controller.rb
# frozen_string_literal: true

require "dry/matcher/result_matcher"
require 'wedding_invite/authentication/use_cases/user_attempts_login'

module App
  class SessionsController < BaseController
    def new
      @form = Authentication::Forms::Login.new
    end

    def create
      Dry::Matcher::ResultMatcher.call(user_attempts_login_result) do |matcher|
        matcher.success do |phone_number|
          session[:verifying_login_for_phone_number] = phone_number
          redirect_to new_app_verification_path
        end

        matcher.failure do |errors|
          @form = login_form.with_errors(errors)
          render :new
        end
      end
    end

    private

    PERMITTED_CREATE_ATTRIBUTES = %i[phone_number]

    def create_params
      params.require(:app_authentication_forms_login).permit(*PERMITTED_CREATE_ATTRIBUTES)
    end

    def login_form
      @login_form ||= Authentication::Forms::Login.new(params: create_params.to_h)
    end

    def user_attempts_login_parameters
      login_form.to_parameter_object
    end

    def user_attempts_login_result
      WeddingInvite::Authentication::UseCases::UserAttemptsLogin.new(
        user_attempts_login_parameters,
        authentication_persistence,
        messaging_service_provider
      ).result
    end
  end
end

app/controllers/app/settings_controller.rb
# frozen_string_literal: true

require "dry/matcher/result_matcher"

module App
  class SettingsController < BaseController
    requires_user_to_be_logged_in
    uses_navigation_screen

    def index
    end
  end
end

app/controllers/app/setup_controller.rb
# frozen_string_literal: true

require "dry/matcher/result_matcher"

module App
  class SetupController < BaseController
    requires_user_to_be_logged_in
    uses_navigation_screen

    def show
      @setup_dashboard = Presenters::SetupDashboard.new(current_wedding)
    end
  end
end

app/controllers/application_controller.rb
require 'turbolinks'

class ApplicationController < ActionController::Base
  include Turbolinks::Redirection
end

app/helpers/app/form_helper.rb
# frozen_string_literal: true

module App
  module FormHelper
    def render_form_errors(form)
      render 'app/forms/errors', errors: form.errors
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/app/app/_navigation.html.erb
<nav class="Navigation">
  <% @navigation.items.each do |item| %>
    <%
    # TODO: Move to helper
    item_classes = ['Navigation__item']
    item_classes << 'Navigation__item--active' if item.active?
    %>
    <%= link_to item.path, class: item_classes do %>
      <%= inline_svg item.icon, class: "Navigation__item__icon" %>
      <span class="Navigation__item__label"><%= item.label %></span>
    <% end %>
  <% end %>
</nav>

app/views/app/app/index.html.erb
<div class="SplashScreen animated fadeIn">
  <%= image_tag 'white-logo.svg', class: 'SplashScreen__logo animated fadeInDown' %>
  <h1 class="SplashScreen__heading animated fadeInUp">Create your free wedding invite website</h1>
  <%= link_to 'Get Started', new_app_signup_stage_one_path, class: 'SplashScreen__button Button Button--primary Button--full-width' %>
  <%= link_to 'Login', new_app_session_path, class: 'SplashScreen__button Button Button--secondary Button--full-width' %>
  <%= link_to 'Find out more', app_about_path, class: 'SplashScreen__more' %>
</div>

app/views/layouts/_screen.html.erb
<div class="Screen" data-controller="screen">
  <% if content_for?(:screen_back_path) || content_for?(:screen_title) %>
    <div class="Screen__header" data-target="screen.header">
      <% if content_for? :screen_back_path %>
        <%= link_to content_for(:screen_back_path), class: 'Screen__header__back' do %>
          <%= image_tag 'app/back-button.svg', class: 'Icon Icon--grey' %>
        <% end %>
      <% end %>
      <% if content_for? :screen_title %>
        <h2 class="Screen__header__title"><%= content_for :screen_title %></h2>
      <% end %>
    </div>
  <% end %>

  <%
  screen_content_base_class = 'Screen__content'
  screen_content_classes = [screen_content_base_class]
  screen_content_classes << "#{screen_content_base_class}--with-title" if content_for? :screen_title
  %>
  <div data-action="scroll->screen#handleScroll" class="<%= screen_content_classes.join(' ') %>">
    <%= yield %>
  </div>

  <% if content_for? :screen_footer %>
    <div class="Screen__footer Screen__footer--floating <%= content_for(:screen_footer_class) %>">
      <%= content_for :screen_footer %>
    </div>
  <% end %>
</div>

app/views/layouts/_screen_with_navigation.html.erb
<%= render layout: 'layouts/screen' do %>
  <% content_for :screen_footer_class, 'Screen__footer--with-background' %>
  <% content_for :screen_footer do %>
    <%= render partial: 'app/app/navigation' %>
  <% end %>
  <%= yield %>
<% end %>

app/views/layouts/app.html.erb
<% content_for :webpack_packs do %>
  <%= stylesheet_pack_tag 'app', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'app', 'data-turbolinks-track': 'reload' %>
<% end %>
<%= render template: 'layouts/application' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= content_for :meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= content_for :webpack_packs %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>