config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: 'app', as: 'app' do
    root to: 'app#index'

    resources :sessions, only: %i[new create]
    resources :verifications, only: %i[new create]
    resource :setup, controller: 'setup', only: %i[show]
    resources :settings, only: %i[index show]


    namespace :signup do
      resource :stage_one, controller: 'stage_one', only: %i[new create]
      resource :stage_two, controller: 'stage_two', only: %i[new create]
      resource :stage_three, controller: 'stage_three', only: %i[new create]
      resource :complete, controller: 'complete', only: %i[show]
    end

    scope module: 'static_content' do
      get :about
    end
  end
end

app/controllers/app/signup/abstract_signup_controller.rb
# frozen_string_literal: true

require 'app/signup/factories/persistence'

module App
  module Signup
    # Abstract controller for signup controllers to inherit from giving them access to
    # #signup_persistence.
    class AbstractSignupController < BaseController
      private

      def signup_persistence
        @signup_persistence ||= Factories::Persistence.new(session).manufacture
      end
    end
  end
end

app/controllers/app/signup/complete_controller.rb
# frozen_string_literal: true

module App
  module Signup
    class CompleteController < AbstractSignupController
      def show
        @complete_signup = signup_persistence.load_complete_signup
      end
    end
  end
end

app/controllers/app/signup/stage_one_controller.rb
# frozen_string_literal: true

require 'app/signup/factories/stage_one_form'
require 'app/signup/forms/stage_one'
require 'wedding_invite/signup/use_cases/user_fills_in_stage_one'
require "dry/matcher/result_matcher"

module App
  module Signup
    class StageOneController < AbstractSignupController
      def new
        @form = Factories::StageOneForm.new(signup_persistence).manufacture
      end

      def create
        Dry::Matcher::ResultMatcher.call(user_fills_in_stage_one_result) do |matcher|
          matcher.success do |_stage_one|
            redirect_to new_app_signup_stage_two_path
          end

          matcher.failure do |errors|
            @form = populated_stage_one_form.with_errors(errors)
            render :new
          end
        end
      end

      private

      PERMITTED_CREATE_ATTRIBUTES = %i[
        forename
        surname
        mobile_phone_number
        partner_forename
        partner_surname
        partner_mobile_phone_number
      ]

      def create_params
        params.require(:app_signup_forms_stage_one).permit(*PERMITTED_CREATE_ATTRIBUTES)
      end

      def populated_stage_one_form
        @populated_stage_one_form ||= Forms::StageOne.new(params: create_params.to_h)
      end

      def user_fills_in_stage_one_parameters
        populated_stage_one_form.to_parameter_object
      end

      def user_fills_in_stage_one_result
        WeddingInvite::Signup::UseCases::UserFillsInStageOne.new(
          user_fills_in_stage_one_parameters,
          signup_persistence
        ).result
      end
    end
  end
end

app/controllers/app/signup/stage_three_controller.rb
# frozen_string_literal: true

require 'app/signup/factories/stage_two_form'

module App
  module Signup
    class StageThreeController < AbstractSignupController
      def new
        @form = Forms::StageThree.new
      end

      def create
        Dry::Matcher::ResultMatcher.call(user_fills_in_stage_three_result) do |matcher|
          matcher.success do |_stage_three|
            redirect_to app_signup_complete_path
          end

          matcher.failure do |errors|
            @form = populated_stage_three_form.with_errors(errors)
            render :new
          end
        end
      end

      private

      PERMITTED_CREATE_ATTRIBUTES = %i[
        date
        terms_agreed
      ]

      def create_params
        params.require(:app_signup_forms_stage_three).permit(*PERMITTED_CREATE_ATTRIBUTES)
      end

      def user_fills_in_stage_three_parameters
        populated_stage_three_form.to_parameter_object
      end

      def populated_stage_three_form
        @populated_stage_three_form ||= Forms::StageThree.new(params: create_params.to_h)
      end

      def user_fills_in_stage_three_result
        WeddingInvite::Signup::UseCases::UserFillsInStageThree.new(
          user_fills_in_stage_three_parameters,
          signup_persistence
        ).result
      end
    end
  end
end

app/controllers/app/signup/stage_two_controller.rb
# frozen_string_literal: true

require 'app/signup/factories/stage_two_form'

module App
  module Signup
    class StageTwoController < AbstractSignupController
      def new
        @form = Factories::StageTwoForm.new(signup_persistence).manufacture
      end

      def create
        Dry::Matcher::ResultMatcher.call(user_fills_in_stage_two_result) do |matcher|
          matcher.success do |_stage_two|
            redirect_to new_app_signup_stage_three_path
          end

          matcher.failure do |errors|
            @form = populated_stage_two_form.with_errors(errors)
            render :new
          end
        end
      end

      private

      PERMITTED_CREATE_ATTRIBUTES = %i[
        name
        domain
      ]

      def create_params
        params.require(:app_signup_forms_stage_two).permit(*PERMITTED_CREATE_ATTRIBUTES)
      end

      def user_fills_in_stage_two_parameters
        populated_stage_two_form.to_parameter_object
      end

      def populated_stage_two_form
        @populated_stage_two_form ||= Forms::StageTwo.new(params: create_params.to_h)
      end

      def user_fills_in_stage_two_result
        WeddingInvite::Signup::UseCases::UserFillsInStageTwo.new(
          user_fills_in_stage_two_parameters,
          signup_persistence
        ).result
      end
    end
  end
end

app/views/app/signup/stage_three/new.html.erb
<% content_for :screen_back_path, new_app_signup_stage_one_path %>
<% content_for :screen_title, 'Signup' %>

<%= render layout: 'layouts/screen' do %>
  <div class="Signup Signup--stage-three">
    <%= form_with model: @form, url: app_signup_stage_three_path, class: 'Form', local: true do |f| %>
      <%= render_form_errors @form %>
      <div class="Form__section">
        <h3>And finally, when is your wedding?</h3>
        <div class="Form__control">
          <%= f.date_field :date, placeholder: 'Your wedding date', required: true %>
        </div>
      </div>
      <div class="Form__section">
        <h3>Terms &amp; Privacy</h3>
        <div class="Signup__terms">
          <div class="Signup__terms__content">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</p>
          </div>
        </div>
        <div class="Form__control Signup__terms-check" data-controller="round-label-checkbox">
          <%= f.label :terms_agreed, class: 'Form__control__round-label' do %>
            <%= f.check_box :terms_agreed, { 'data-action': 'change->round-label-checkbox#handleChange', 'data-target': 'round-label-checkbox.input' } %>
            <%= f.label :terms_agreed, '✓', class: 'Form__control__round-label__circle' %>
            <span class="Form__control__round-label__content">I have read and agree to the terms &amp; privacy policies</span>
          <% end %>
        </div>
      </div>
      <div class="Form__action">
        <%= f.submit 'Signup', class: 'Button Button--primary Button--full-width', data: { disable_with: 'Please wait...' } %>
      </div>
    <% end %>
  </div>
<% end %>