config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: 'app', as: 'app' do
    root to: 'app#index'

    resources :sessions, only: %i[new create]
    resources :verifications, only: %i[new create]
    resource :setup, controller: 'setup', only: %i[show]
    resources :settings, only: %i[index show]


    namespace :signup do
      resource :stage_one, controller: 'stage_one', only: %i[new create]
      resource :stage_two, controller: 'stage_two', only: %i[new create]
      resource :stage_three, controller: 'stage_three', only: %i[new create]
      resource :complete, controller: 'complete', only: %i[show]
    end

    scope module: 'static_content' do
      get :about
    end
  end
end

app/controllers/app/verifications_controller.rb
# frozen_string_literal: true

require "dry/matcher/result_matcher"
require 'wedding_invite/authentication/use_cases/user_verifies_login'

module App
  class VerificationsController < BaseController
    def new
      @form = Authentication::Forms::Verify.new(
        params: form_params
      )
    end

    def create
      Dry::Matcher::ResultMatcher.call(user_verifies_login_result) do |matcher|
        matcher.success do |login_token|
          session[:verifying_login_for_phone_number] = nil
          session_manager.use_login_token(login_token)
          redirect_to app_root_path
        end

        matcher.failure do |_|
          @form = verify_form.with_error_message(
            "That code doesn't look quite right, re-enter the code or try again.",
            override_params: form_params
          )
          render :new
        end
      end
    end

    private

    PERMITTED_CREATE_ATTRIBUTES = %i[phone_number authentication_code]

    def create_params
      params.require(:app_authentication_forms_verify).permit(*PERMITTED_CREATE_ATTRIBUTES)
    end

    def form_params
      { phone_number: decoded_phone_number }
    end

    def decoded_phone_number
      session.fetch(:verifying_login_for_phone_number)
    end

    def verify_form
      @verify_form ||= Authentication::Forms::Verify.new(params: create_params.to_h)
    end

    def user_verifies_login_parameters
      verify_form.to_parameter_object
    end

    def user_verifies_login_result
      WeddingInvite::Authentication::UseCases::UserVerifiesLogin.new(
        user_verifies_login_parameters,
        authentication_persistence
      ).result
    end
  end
end

app/views/app/verifications/new.html.erb
<% content_for :screen_back_path, new_app_session_path %>
<%= render layout: 'layouts/screen' do %>
  <div class="Verify">
    <%= image_tag 'app/verify.svg', class: 'Verify__icon animated fadeIn' %>
    <h3 class="Verify__heading animated fadeInDown">Lookout for the text</h3>
    <p class="Verify__explanation animated fadeInUp">We’ve just sent you a text, enter the code from the message below to login:</p>

    <%= form_with model: @form, url: app_verifications_path, class: 'Form', local: true, html: { 'data-controller': 'verify' } do |f| %>
      <%= f.hidden_field :phone_number %>
      <%= render_form_errors @form %>
      <div class="Form__section">
        <div class="Form__control Verify__code" data-target="verify.codeControl">
          <%= f.text_field :authentication_code, autocomplete: 'one-time-code', autofocus: true, placeholder: '****', class: 'Verify__code__input', pattern: '\d*', maxlength: 4, novalidate: true, 'data-action': 'textInput->verify#submitWhenComplete input->verify#submitWhenComplete blur->verify#submitWhenComplete change->verify#submitWhenComplete keypress->verify#submitWhenComplete', 'data-target': 'verify.codeInput' %>
          <%= image_tag 'app/loading.svg', class: 'Verify__code__loading' %>
        </div>
      </div>
    <% end %>

    <div class="Verify__retry">
      <%= link_to "Haven't received it? Retry", new_app_session_path, class: 'Verify__retry__link' %>
    </div>
  </div>
<% end %>